### ISSUE TITLE
 backend does not boot

### ISSUE THREAD

**Issue by mauriciolacerda** [Datlyfe/jira_clone#1]
yarn run v1.22.0
$ node dist/index.js
internal/modules/cjs/loader.js:796
Error: Cannot find module 'D:\Dev\jira\backend\dist\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by Datlyfe** [comment]
Looks like you didn't build first 
run `yarn build` in the backend diretory before running `yarn start`
or run `yarn dev` if you want to run in development
